# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YkynmfyM942f62dZShYk3K4iWqxj8CJO
"""

import pandas as pd
#from google.colab import files

#discipline = files.upload()
discipline = pd.read_csv('Дисциплины.csv')
#vacans = files.upload()
vacans = pd.read_csv('Вакансии.csv')
#work =  files.upload()
work = pd.read_csv('Должности.csv')
#line_of_plans =  files.upload()
line_of_plans = pd.read_csv('строчки_планов.csv')
#plans = files.upload()
plans = pd.read_csv('планы.csv')

plan_disp1 = {}

for i in range(len(plans['ID'])):
    disciplines_data = []
    for j in range(len(line_of_plans['planId'])):
        if plans['ID'][i] == line_of_plans['planId'][j]:
            disciplines_data.append((line_of_plans['subject'][j], line_of_plans['hours'][j]))
    plan_disp1[plans['Title'][i]] = disciplines_data

data = {}
for i in range(len(discipline['Дисциплина'])):
  if not discipline['Дисциплина'][i] in data:
    data[discipline['Дисциплина'][i]] = set()
    data[discipline['Дисциплина'][i]].add(discipline['ГруппаВакансий'][i])
  else:
    data[discipline['Дисциплина'][i]].add(discipline['ГруппаВакансий'][i])

plan_disp2 = plan_disp1.copy()
for key in plan_disp2.keys():
  work_data = {}
  for i in plan_disp2[key]:
    for j in data.keys():
      if j == i[0]:
        for k in data[j]:
          if not k in work_data:
            work_data[k] = int(i[1])
          else:
            work_data[k] += int(i[1])
  plan_disp2[key] = work_data

plan_disp3 = plan_disp2.copy()
for i in plan_disp3.keys():
  works = {}
  for j in plan_disp3[i]:
    for k in range(len(work['Группа вакансий'])):
      if j == work['Группа вакансий'][k]:
        works[work['Название должности'][k]] = plan_disp3[i][j]
  plan_disp3[i] = works

data = list(set(work['Название должности']))
dct = {}
for i in data:
  works = {}
  for key in plan_disp3.keys():
    for e in plan_disp3[key]:
      works[key] = plan_disp3[key][e]
  dct[i] = works

data = []
for key in dct:
  for i in dct[key]:
    data.append([i, key, str(dct[key][i])])

with open('file.txt', 'w') as f:
  for i in data:
    print(', '.join(i))